#!/usr/bin/env python

Import('env')

env = env.Clone()

env.Append(CXXFLAGS=["-std=c++20", "-g"])
env.Append(CPPDEFINES=["SOTA_MODULE"])

env.Append(CPPPATH=["src"])
env.Append(CPPPATH=["src/tal"])
env.Append(CPPPATH=["src/polyhedron"])
env.Append(CPPPATH=["src/primitives"])
env.Append(CPPPATH=["src/core"])
env.Append(CPPPATH=["src/prism_impl"])
env.Append(CPPPATH=["src/ridge_impl"])
env.Append(CPPPATH=["src/honeycomb"])
env.Append(CPPPATH=["src/misc"])
env.Append(CPPPATH=["src/algo"])

sources = Glob("register_types.cpp")
sources += Glob("src/*.cpp")
sources += Glob("src/polyhedron/*.cpp")
sources += Glob("src/primitives/*.cpp")
sources += Glob("src/core/*.cpp")
sources += Glob("src/prism_impl/*.cpp")
sources += Glob("src/ridge_impl/*.cpp")
sources += Glob("src/honeycomb/*.cpp")
sources += Glob("src/misc/*.cpp")
sources += Glob("src/algo/*.cpp")

env.add_source_files(env.modules_sources, sources)
